export default function Head() {
  return (
    <>
      <title>Next v13 Course</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}

/*
    Esta función devuelve un elemento jsx representando los elementos del encabezado de la página
    Esto se usa para definir el encabeza de una página web, para especificar el titulo de la página,
    el ancho del dispositivo, la escala de la vista inicial, una descripción, etc. Esto es útil
    para los motores de búsqueda y el SEO, para ayudar a que los motores de búsqueda lleguen a la página
    y puedan extraer la información más relevante
*/
